import { useState } from 'react';
import { ChevronDown, ChevronRight } from 'lucide-react';
import { PageHeader } from '../components/PageHeader.tsx';
import { DocBody } from '../components/MarkdownViewer.tsx';
import { usePolling } from '../lib/api.ts';
import { personaColor, personaIcon } from '../lib/persona-colors.ts';

const SCOPE = 'reports';

// Filename → primary author persona, mirrored from the v3 persona library.
const FILE_AUTHOR: Record<string, string> = {
  'analysis-reports.md': '+operation-manager',
  'content-reports.md': '+copywriter',
  'delivery-reports.md': '+delivery-manager',
  'growth-reports.md': '+growth-expert',
  'legal-reports.md': '+compliance-expert',
  'product-requirements.md': '+product-manager',
  'release-notes.md': '+operation-manager',
  'security-reports.md': '+security-engineer',
  'status-reports.md': '+operation-manager',
  'tech-requirements.md': '+engineering-manager',
  'test-reports.md': '+qa-engineer',
};

export function ReportsRoute() {
  const { data, error, loading } = usePolling<{ files: { name: string }[] }>(
    `/api/docs/${SCOPE}`,
    15_000,
  );
  const files = (data?.files ?? []).map((f) => f.name);
  const total = files.length;

  const [expanded, setExpanded] = useState<string | null>(null);

  return (
    <div className="flex flex-col h-full min-h-0">
      <PageHeader
        title="Reports"
        subtitle="Generated artifacts — analysis, status, security, delivery"
        actions={
          total > 0 ? (
            <span
              className="text-[9px] font-bold uppercase tracking-[0.06em] px-1.5 py-0.5 rounded leading-tight"
              style={{ color: 'var(--warning)', background: 'rgba(245,158,11,0.12)' }}
            >
              {total} pending review
            </span>
          ) : null
        }
      />

      <div className="flex-1 min-h-0 overflow-y-auto px-6 py-5 flex flex-col gap-2.5">
        {error && <p className="text-[13px] text-danger">{error}</p>}
        {loading && !data && <p className="text-[13px] text-tx-3">loading reports…</p>}
        {!loading && total === 0 && (
          <div className="border border-dashed border-border-default rounded-md px-5 py-8 text-center">
            <p className="text-[13px] text-tx-2">No reports yet</p>
            <p className="mt-1 text-[12px] text-tx-3">
              Personas write reports into workspace/reports/ as the pipeline runs.
            </p>
          </div>
        )}
        {files.map((f) => (
          <ReportCard
            key={f}
            file={f}
            expanded={expanded === f}
            onToggle={() => setExpanded((cur) => (cur === f ? null : f))}
          />
        ))}
      </div>
    </div>
  );
}

function ReportCard({
  file,
  expanded,
  onToggle,
}: {
  file: string;
  expanded: boolean;
  onToggle: () => void;
}) {
  const author = FILE_AUTHOR[file] ?? null;
  const color = personaColor(author);
  const Icon = personaIcon(author);
  const title = humanize(file);

  return (
    <article className="border border-border-default rounded-md bg-bg-0 hover:border-border-strong transition-colors duration-200">
      <button
        type="button"
        onClick={onToggle}
        className="w-full text-left px-4 py-3"
      >
        <header className="flex items-center gap-3">
          {expanded ? (
            <ChevronDown className="w-3.5 h-3.5 text-tx-3 shrink-0" />
          ) : (
            <ChevronRight className="w-3.5 h-3.5 text-tx-3 shrink-0" />
          )}
          <span className="flex-1 text-[13px] text-tx-1 font-medium">{title}</span>
          <span
            className="text-[9px] font-bold uppercase tracking-[0.06em] px-1.5 py-0.5 rounded leading-tight"
            style={{ color: 'var(--tx-3)', background: 'rgba(107,101,119,0.18)' }}
          >
            Template
          </span>
          <span className="mono text-[11px] text-tx-3 shrink-0">{file}</span>
        </header>
        {author && (
          <div className="flex items-center gap-2 mt-2 ml-6 text-[11px] text-tx-3">
            <span
              className="inline-flex items-center justify-center w-[18px] h-[18px] rounded-full"
              style={{ background: color, color: '#0A0814' }}
              aria-hidden
            >
              <Icon size={10} strokeWidth={2.5} />
            </span>
            <span>
              Generated by{' '}
              <code className="mono" style={{ color }}>
                {author}
              </code>
            </span>
          </div>
        )}
      </button>
      {expanded && (
        <div className="border-t border-border-subtle">
          <DocBody scope={SCOPE} file={file} />
        </div>
      )}
    </article>
  );
}

function humanize(filename: string): string {
  return filename
    .replace(/\.md$/, '')
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}
